<a href="https://colab.research.google.com/github/Akshitha1330/B20_1330/blob/main/LAB-3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
# writing to a file
# open file in write mode
fp = open("example.txt", "w")

#write text to file
fp.write("Hello\n")
fp.write("this is file handling in python\n")
fp.write("sr university\n")
fp.write("Akshitha")
#close file
fp.close()
print("Data written successfully!")

In [7]:
#reading a file
fp=open("example.txt","r")
content=fp.read()
print("file content:\n",content)
fp.close()
fp.close()

file content:
 Hello
this is file handling in python
sr university
Akshitha



In [10]:
#reading line by line
fp=open("example.txt","r")
line1=fp.readline()
print("first line",line1)
line2=fp.readline()
print("second line",line2)
line3=fp.readline()
print("third line",line3)
line4=fp.readline()
print("fourth line",line4)
fp.close()

first line Hello

second line this is file handling in python

third line sr university

fourth line Akshitha



In [11]:
#reading all lines into a list
fp=open("example.txt","r")
lines=fp.readlines()
print("list of lines:\n",lines)
fp.close()

list of lines:
 ['Hello\n', 'this is file handling in python\n', 'sr university\n', 'Akshitha\n']


In [14]:
#appending data to an existing file
fp=open("example.txt","a")
fp.write("third year\n")
fp.close()

In [15]:
#using with statement
#the with statement automatically closes the file
with open("example.txt","r") as fp:
    content=fp.read()
    print("file content:\n",content)

file content:
 Hello
this is file handling in python
sr university
Akshitha
third year
third year
third year



In [18]:
#writing to csv
import csv
with open("data.csv","w",newline="") as fp:
    writer=csv.writer(fp)
    writer.writerows([["Name","Age","Course"],["A",21,"CSE"],["B",20,"ECE"]])

#reading from csv
with open("data.csv","r") as fp:
    reader=csv.reader(fp)
    for row in reader:
        print(row)

['Name', 'Age', 'Course']
['A', '21', 'CSE']
['B', '20', 'ECE']


In [32]:
import numpy as np
#1D Array
arr1=np.array([1,2,3,4,5])
print("1D Array:\n",arr1)
#2D Array
arr2=np.array([[1,2,3],[4,5,6]])
print("2D Array:\n",arr2)
#Zeros Array
zeros_arr=np.zeros((3,4))
print("zeros Array:\n",zeros_arr)
#Ones Array
ones_arr=np.ones((2,3))
print("Ones Array:\n",ones_arr)
#Range of numbers
range_arr=np.arange(2,10,2)
print("Range Array:\n",range_arr)
#Randam Array
randam_arr=np.random.rand(2,3)
print("Randam Array:\n",randam_arr)

1D Array:
 [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
zeros Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Range Array:
 [2 4 6 8]
Randam Array:
 [[0.30364828 0.39926152 0.31219068]
 [0.80754098 0.12743428 0.65176963]]


In [35]:
#Array Attributes
arr=np.array([[1,2,3],[4,5,6]])
print("Array:\n",arr)
print("Shape:",arr.shape)
print("Dimension:",arr.ndim)
print("Size:",arr.size)
print("Data Type:",arr.dtype)
print("Item Size:",arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimension: 2
Size: 6
Data Type: int64
Item Size: 8


In [38]:
#Array Indexing and Slicing
arr=np.array([10,20,30,40,50])
print("Array:",arr)
print("First Element:",arr[0])
print("Last Element:",arr[-1])
print("Slice:",arr[1:4])
print("Every second element",arr[::2])
#2D indexing
arr2=np.array([[1,2,3],[4,5,6]])
print("Array:\n",arr2)
print("Element at row 1,col 2 :",arr2[0,1])
print("second row",arr2[1,:])
print("second column",arr2[:,1])

Array: [10 20 30 40 50]
First Element: 10
Last Element: 50
Slice: [20 30 40]
Every second element [10 30 50]
Array:
 [[1 2 3]
 [4 5 6]]
Element at row 1,col 2 : 2
second row [4 5 6]
second column [2 5]


In [41]:
#Array Operations
#Arithmetic Operations
a=np.array([1,2,3])
b=np.array([4,5,6])
print("Addition:",a+b)
print("Subtraction:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)
print("Power:",a**2)
#Mathematical Functions
arr=np.array([0,np.pi/2,np.pi])
print("Sin:",np.sin(arr))
print("Cos:",np.cos(arr))
print("Tan:",np.tan(arr))
print("Exp:",np.exp(arr))
print("Sqrt:",np.sqrt(arr))

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Power: [1 4 9]
Sin: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Cos: [ 1.000000e+00  6.123234e-17 -1.000000e+00]
Tan: [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
Exp: [ 1.          4.81047738 23.14069263]
Sqrt: [0.         1.25331414 1.77245385]


In [42]:
#aggregate Functions
arr=np.array([[1,2,3],[4,5,6]])
print("Array:\n",arr)
print("Sum:",np.sum(arr))
print("Min:",np.min(arr))
print("Max:",np.max(arr))
print("Mean:",np.mean(arr))
print("Median:",np.median(arr))
print("Standard Deviation:",np.std(arr))
print("Sum along axis 0:",np.sum(arr,axis=0)) #column wise sum
print("Sum along axis 1:",np.sum(arr,axis=1)) #row wise sum

Array:
 [[1 2 3]
 [4 5 6]]
Sum: 21
Min: 1
Max: 6
Mean: 3.5
Median: 3.5
Standard Deviation: 1.707825127659933
Sum along axis 0: [5 7 9]
Sum along axis 1: [ 6 15]


In [45]:
#Broadcasting
# it allows operationson arrays of different shapes
a=np.array([1,2,3])
b=5
print("Add scalar to array:",a+b)
c=np.array([[1],[2],[3]])
d=np.array([4,5,6])
print("Broadcasted sum\n:",c+d)

Add scalar to array: [6 7 8]
Broadcasted sum
: [[5 6 7]
 [6 7 8]
 [7 8 9]]


In [46]:
#Matrix Operations
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])l
print("Matrix Multiplication:\n",np.dot(A,B))
print("Matrix Transpose:\n",A.T)
print("Matrix Inverse:\n",np.linalg.inv(A))
print("Matrix Determinant:\n",np.linalg.det(A))

Matrix Multiplication:
 [[19 22]
 [43 50]]
Matrix Transpose:
 [[1 3]
 [2 4]]
Matrix Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Matrix Determinant:
 -2.0000000000000004


In [47]:
#Sample Program - Student Analsis
import numpy as np
# Marks of students in 3 subjects
marks = np.array([
[85, 90, 88],
[78, 81, 85],
[92, 89, 95]S
])
print("Average marks per student:", np.mean(marks, axis=1))
print("Average marks per subject:", np.mean(marks, axis=0))
print("Highest marks in each subject:", np.max(marks, axis=0))
print("Lowest marks in each subject:", np.min(marks, axis=0))

Average marks per student: [87.66666667 81.33333333 92.        ]
Average marks per subject: [85.         86.66666667 89.33333333]
Highest marks in each subject: [92 90 95]
Lowest marks in each subject: [78 81 85]
