<a href="https://colab.research.google.com/github/Akshitha1330/B20_1330/blob/main/LAB2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
l=[10,99.9,'cse']
for i in l:
  print(type(i),i)

<class 'int'> 10
<class 'float'> 99.9
<class 'str'> cse


In [3]:
l=[10,20,10,20,10,20]
print(l)

[10, 20, 10, 20, 10, 20]


In [10]:
l=[10,20,30,40]
l.append(50)
print(l)
l.pop()
print(l)
l.remove(30)
print(l)
l.insert(2,100)
print(l)
l.reverse()
print(l)
l.sort()
print(sum(l))
print(min(l))
print(max(l))
print(l)

[10, 20, 30, 40, 50]
[10, 20, 30, 40]
[10, 20, 40]
[10, 20, 100, 40]
[40, 100, 20, 10]
170
10
100
[10, 20, 40, 100]


In [11]:
student=[[10,20],[30,40],[50,60],[70,80]]
print(student)

[[10, 20], [30, 40], [50, 60], [70, 80]]


In [14]:
student=[[10,20],[30,40],[50,60],[70,80]]
print(student)

[[10, 20], [30, 40], [50, 60], [70, 80]]


In [16]:
t=(10,20,30,40)
print(t)
t=(10,20,30,10,20)
print(t)
t=(10,99.9,'cse')
for i in t:
  print(type(i),i)

(10, 20, 30, 40)
(10, 20, 30, 10, 20)
<class 'int'> 10
<class 'float'> 99.9
<class 'str'> cse
not found


In [17]:
t=(10,20,30,40)
if 20 in t:
  print('found')
else:
  print('not found')

found


In [19]:
t=(1,2,3,2,3,2,4)
print(t.count(2))
print(t.index(4))

3
6


In [22]:
l=[10,20,30,40]
my_tuple=tuple(l)
print(my_tuple)

s=((10,20),(100,50))
print(s)

(10, 20, 30, 40)
((10, 20), (100, 50))


In [32]:
student={"name":"python","id":"101","branch":"cse"}
print(student.keys())
print(student.values())
print(student.items())
for key,value in student.items():
    print(key,value)

student["college"]="sru"
print(student)
student["specialisation"]="AIML"
print(student)
del student["specialisation"]
print(student)


student1={101:{"name":"c","id":"1"},"102":{"name":"python","id":"2"}}
print(student1)
print(student1[101])
print(student1[101]["name"])


dict_keys(['name', 'id', 'branch'])
dict_values(['python', '101', 'cse'])
dict_items([('name', 'python'), ('id', '101'), ('branch', 'cse')])
name python
id 101
branch cse
{'name': 'python', 'id': '101', 'branch': 'cse', 'college': 'sru'}
{'name': 'python', 'id': '101', 'branch': 'cse', 'college': 'sru', 'specialisation': 'AIML'}
{'name': 'python', 'id': '101', 'branch': 'cse', 'college': 'sru'}
{101: {'name': 'c', 'id': '1'}, '102': {'name': 'python', 'id': '2'}}
{'name': 'c', 'id': '1'}
c


In [28]:
print("10\t20\n30\t40\n50\t60")

10	20
30	40
50	60


In [30]:
l=[[10,20],[30,40],[50,60]]
for i in l:
  print(*i)

10 20
30 40
50 60


In [33]:
l=[[10,20],[30,40],[50,60]]
for i in l:
  print(i)

[10, 20]
[30, 40]
[50, 60]


In [37]:
s={1,2,3,4}
print(s)
s={1,2,3,4,1,2,3,4}
print(s)
for i in s:
  print(i)
if 2 in s:
  print("f");
else:
  print("nf")

{1, 2, 3, 4}
{1, 2, 3, 4}
1
2
3
4
f


In [43]:
a={1,2,3,4}
b={3,4,5,6}
print(a.union(b))
print(a.intersection(b))
print(a.difference(b))
print(b.difference(a))
print("union",a|b)
print("intersection",a&b)
print("difference",a-b)
print("difference",b-a)
print(a.symmetric_difference(b))
print("symmetric_difference",a^b)

{1, 2, 3, 4, 5, 6}
{3, 4}
{1, 2}
{5, 6}
union {1, 2, 3, 4, 5, 6}
intersection {3, 4}
difference {1, 2}
difference {5, 6}
{1, 2, 5, 6}
symmetric_difference {1, 2, 5, 6}


In [44]:
s={1,2,3}
s.add(4)
print(s)
s.remove(2)
print(s)
s.clear()
print(s)

{1, 2, 3, 4}
{1, 3, 4}
set()


In [48]:
import numpy as np
marks = np.array([[85, 78, 92], [70, 65, 80],  [90, 88, 94],  [60, 75, 70],  [95, 85, 99] ])
avg_marks = np.mean(marks)
min_marks = np.min(marks)
max_marks = np.max(marks)
print(avg_marks)
print(min_marks)
print(max_marks)

print("Marks of Student 3:", marks[2])
print("Marks of Students 2 to 4: ", marks[1:4])

excellent= marks >80
print(excellent)

each_subject = marks.T
print("EACH SUBJECT MARKS", each_subject)

81.73333333333333
60
99
Marks of Student 3: [90 88 94]
Marks of Students 2 to 4:  [[70 65 80]
 [90 88 94]
 [60 75 70]]
[[ True False  True]
 [False False False]
 [ True  True  True]
 [False False False]
 [ True  True  True]]
EACH SUBJECT MARKS [[85 70 90 60 95]
 [78 65 88 75 85]
 [92 80 94 70 99]]
